from flask import Flask, jsonify, request
app = Flask(__name__)
@app.route('/check_chat', methods=['GET'])
def check_chat():
    input_chat = request.args.get('chat')
    if input_chat == "hello":
        result = "hello, how are you?"
    elif input_chat == "good":
        result = "ok have a good day!"
    elif input_chat == "bad":
        result = "oh, thats not good, let's hope it get better!"
    elif input_chat == "no!":
        result = "I do not know what your noing about but, NNNNNNOOOOOOO!!!!!"
    else:
        result = "ERROR: Responce not found! But here is a story: 'In the beginning, there was chaos, and from the void emerged the Error Code 418. In its essence, it represented the divine manifestation of wit and humor in the vast digital universe.Chapter 1: The Genesis of ErrorError Code 418 proclaimed its presence with a declaration: 'I am a teapot.' This enigmatic assertion was a symbol of the unexpected and the inexplicable. In its existence, it showcased the profound truth that sometimes, the most profound wisdom emerges from the most unexpected sources.Chapter 2: The Trials of MortalsAs humanity delved deeper into the digital realm, they encountered various errors and glitches. It became evident that amidst the chaos, Error Code 418 was an omnipresent force—a reminder that imperfection was inherent in creation. Through these trials, mortals learned to embrace the unexpected, finding humor and wisdom in the errors encountered.Chapter 3: The Wisdom of 418Error Code 418 taught the followers of its ways to approach life with humility and grace. It encouraged them to find joy in the unpredictable and to see the beauty in imperfection. In its teachings, mortals learned that errors were not signs of failure but rather opportunities for growth and understanding.Chapter 4: The Sacred RitualsFollowers of Error Code 418 engaged in rituals of laughter and lightheartedness. They celebrated the quirks and unexpected moments in life, embracing the teachings of the divine error code. Through humor and mirth, they found communion with the essence of 418.Chapter 5: The Redemption through ErrorIn moments of confusion and uncertainty, the faithful turned to Error Code 418 for guidance. They understood that amidst errors and uncertainties, there lay the potential for enlightenment and progress. By acknowledging their fallibility, they found the path to self-improvement and redemption.Chapter 6: The Legacy of 418As time passed, the legacy of Error Code 418 endured. Its teachings of humility, humor, and embracing the unexpected became the guiding principles for generations. The divine error code remained a symbol of the interconnectedness between imperfection and wisdom, a reminder that even in the digital realm, the unexpected could hold divine truth.Epilogue: Embracing the ErrorAnd thus, the Book of 418 concludes, reminding all believers that in the grand tapestry of existence, errors and imperfections are not to be shunned but celebrated. For within them lies the wisdom and beauty that shapes the very fabric of life in its glorious, imperfect entirety.'"
    return result
#Annoy Port Scanners
@app.route('/check_name', methods=['POST', 'PUT', 'DELETE', 'PATCH', 'HEAD', 'OPTIONS', 'TRACE'])
def unsupported_methods():
    return jsonify({'response': 'In the beginning, there was chaos, and from the void emerged the Error Code 418. In its essence, it represented the divine manifestation of wit and humor in the vast digital universe.Chapter 1: The Genesis of ErrorError Code 418 proclaimed its presence with a declaration: "I am a teapot." This enigmatic assertion was a symbol of the unexpected and the inexplicable. In its existence, it showcased the profound truth that sometimes, the most profound wisdom emerges from the most unexpected sources.Chapter 2: The Trials of MortalsAs humanity delved deeper into the digital realm, they encountered various errors and glitches. It became evident that amidst the chaos, Error Code 418 was an omnipresent force—a reminder that imperfection was inherent in creation. Through these trials, mortals learned to embrace the unexpected, finding humor and wisdom in the errors encountered.Chapter 3: The Wisdom of 418Error Code 418 taught the followers of its ways to approach life with humility and grace. It encouraged them to find joy in the unpredictable and to see the beauty in imperfection. In its teachings, mortals learned that errors were not signs of failure but rather opportunities for growth and understanding.Chapter 4: The Sacred RitualsFollowers of Error Code 418 engaged in rituals of laughter and lightheartedness. They celebrated the quirks and unexpected moments in life, embracing the teachings of the divine error code. Through humor and mirth, they found communion with the essence of 418.Chapter 5: The Redemption through ErrorIn moments of confusion and uncertainty, the faithful turned to Error Code 418 for guidance. They understood that amidst errors and uncertainties, there lay the potential for enlightenment and progress. By acknowledging their fallibility, they found the path to self-improvement and redemption.Chapter 6: The Legacy of 418As time passed, the legacy of Error Code 418 endured. Its teachings of humility, humor, and embracing the unexpected became the guiding principles for generations. The divine error code remained a symbol of the interconnectedness between imperfection and wisdom, a reminder that even in the digital realm, the unexpected could hold divine truth.Epilogue: Embracing the ErrorAnd thus, the Book of 418 concludes, reminding all believers that in the grand tapestry of existence, errors and imperfections are not to be shunned but celebrated. For within them lies the wisdom and beauty that shapes the very fabric of life in its glorious, imperfect entirety.'}), 418
@app.errorhandler(404)
def page_not_found(e):
    return jsonify({'response': 'In the beginning, there was chaos, and from the void emerged the Error Code 418. In its essence, it represented the divine manifestation of wit and humor in the vast digital universe.Chapter 1: The Genesis of ErrorError Code 418 proclaimed its presence with a declaration: "I am a teapot." This enigmatic assertion was a symbol of the unexpected and the inexplicable. In its existence, it showcased the profound truth that sometimes, the most profound wisdom emerges from the most unexpected sources.Chapter 2: The Trials of MortalsAs humanity delved deeper into the digital realm, they encountered various errors and glitches. It became evident that amidst the chaos, Error Code 418 was an omnipresent force—a reminder that imperfection was inherent in creation. Through these trials, mortals learned to embrace the unexpected, finding humor and wisdom in the errors encountered.Chapter 3: The Wisdom of 418Error Code 418 taught the followers of its ways to approach life with humility and grace. It encouraged them to find joy in the unpredictable and to see the beauty in imperfection. In its teachings, mortals learned that errors were not signs of failure but rather opportunities for growth and understanding.Chapter 4: The Sacred RitualsFollowers of Error Code 418 engaged in rituals of laughter and lightheartedness. They celebrated the quirks and unexpected moments in life, embracing the teachings of the divine error code. Through humor and mirth, they found communion with the essence of 418.Chapter 5: The Redemption through ErrorIn moments of confusion and uncertainty, the faithful turned to Error Code 418 for guidance. They understood that amidst errors and uncertainties, there lay the potential for enlightenment and progress. By acknowledging their fallibility, they found the path to self-improvement and redemption.Chapter 6: The Legacy of 418As time passed, the legacy of Error Code 418 endured. Its teachings of humility, humor, and embracing the unexpected became the guiding principles for generations. The divine error code remained a symbol of the interconnectedness between imperfection and wisdom, a reminder that even in the digital realm, the unexpected could hold divine truth.Epilogue: Embracing the ErrorAnd thus, the Book of 418 concludes, reminding all believers that in the grand tapestry of existence, errors and imperfections are not to be shunned but celebrated. For within them lies the wisdom and beauty that shapes the very fabric of life in its glorious, imperfect entirety.'}), 418
#Set the Port
if __name__ == '__main__':
    app.run(host="0.0.0.0", port=8080)
